changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}}'
kinds:
- label: Added
- label: Changed
- label: Removed
- label: Fixed
- label: Developers
newlines:
  afterChangelogHeader: 1
  beforeChangelogVersion: 1
  endOfVersion: 0
  afterKind: 1
  afterChange: 1
