name: main

on:
  pull_request:
  push:
    branches:
      # Only build on push for master or dev, otherwise branches pushed for PR
      # are built twice
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: ci/build-docker-image
        shell: bash
      - name: Build
        shell: bash
        run: ci/docker-build-game SNAPSHOT=1
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
